### 1. Spliting numpy array(or list) into fixed size of N list
- split an array with 100,000 elements into 4 list

In [1]:
import numpy as np

arr = np.random.random(100000)
res = np.array_split(arr, 4)

In [2]:
res

[array([0.02776865, 0.67532739, 0.88907734, ..., 0.52813193, 0.13780138,
        0.50100955]),
 array([0.38377022, 0.66682547, 0.6400858 , ..., 0.59054295, 0.23278122,
        0.59199018]),
 array([0.57756008, 0.78727528, 0.00201975, ..., 0.85257492, 0.604831  ,
        0.02425713]),
 array([0.36494613, 0.75409481, 0.70433492, ..., 0.30785207, 0.77159689,
        0.06046045])]